services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=tjv'
      - 'POSTGRES_USER=admin'
      - 'POSTGRES_PASSWORD=tjv'
    ports:
      - '5432:5432'
    volumes:
    - "./src/main/resources/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d"
